# Generated by Django 5.0.7 on 2024-07-13 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todomodel_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='task',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
